#!/bin/bash

# Copyright 2018 Stellar Development Foundation and contributors. Licensed
# under the Apache License, Version 2.0. See the COPYING file at the root
# of this distribution or at http://www.apache.org/licenses/LICENSE-2.0

BASE_INSTANCE="$1"
TESTS="$2"

GRAVITY_DEFAULT_TEST_PARAMS="--ll fatal -w NoTests -a -r simple"
if [[ "$ALL_VERSIONS" != "" ]]; then
    GRAVITY_DEFAULT_TEST_PARAMS="$GRAVITY_DEFAULT_TEST_PARAMS --all-versions"
fi

: ${GRAVITY_TEST_PARAMS=$GRAVITY_DEFAULT_TEST_PARAMS}

./gravity test $GRAVITY_TEST_PARAMS --base-instance $BASE_INSTANCE "$TESTS" 2> /dev/null
R=$?
if [[ $R -ne 0 ]] ; then
    echo "Test failed, rerunning with debugger"
    echo ./gravity test $GRAVITY_TEST_PARAMS --base-instance $BASE_INSTANCE "$TESTS"
    lldb -o 'r'  -o 'bt' -o 'exit' -- ./gravity test $GRAVITY_TEST_PARAMS --base-instance $BASE_INSTANCE "$TESTS"
fi
exit $R
